[package]
name = "linear_classifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
rand = "0.9.0-alpha.1"

[lib]
name = "linear_classifier"
crate-type = ["cdylib"]